import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/common/sidebar";
import { Header } from "@/common/header";
// import { MobileHeader } from "@/common/mobileHeader";
import { MobileFooter } from "@/common/mobileFooter";
import { Toaster } from 'sonner';
import QueryProvider from '@/components/queryProvider';
import { CartProvider } from "@/context/cart.context";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <QueryProvider>
          <CartProvider>
            <div className="flex h-screen">
              <Sidebar />

              <div className="flex-1 flex flex-col h-screen overflow-hidden">
                <Header />

                {/* MobileHeader will now be rendered inside individual pages if needed */}

                <main className="flex-1 overflow-auto p-4">
                  {children}
                </main>

                <MobileFooter />
              </div>
            </div>
          </CartProvider>
        </QueryProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}

